カレンダーmockの修正 (#46)

diff --git a/.github/workflows/ita-test.yml b/.github/workflows/ita-test.yml
--- a/.github/workflows/ita-test.yml
+++ b/.github/workflows/ita-test.yml
@@ -109,10 +109,53 @@ jobs:
             'http://localhost:3000/api/races/keirin/race?startDate=2024-10-01&finishDate=2024-11-01' \
             -H 'accept: application/json')
 
-          # Final GET Response Check: 要素数が31個であることを確認
+          # Final GET Response Check: 要素数が372個であることを確認
           item_count=$(echo "$response" | jq '. | length')
           if [[ "$item_count" -ne 372 ]]; then
             echo "❌ Updated GET request failed. Expected 372 items but got $item_count items."
+            exit 1
+          fi
+
+          echo "✅ All checks passed successfully."
+
+      - name: Curl API for Keirin Calendar
+        run: |
+          # Initial GET request
+          response=$(curl -s -X 'GET' \
+            'http://localhost:3000/api/races/keirin/calendar?startDate=2024-10-01&finishDate=2024-11-01' \
+            -H 'accept: application/json')
+
+          # Initial GET Response Check
+          if [[ "$response" != "[]" ]]; then
+            echo "❌ Initial GET request failed. Expected [], but got $response"
+            exit 1
+          fi
+
+          # POST request
+          post_response=$(curl -s -o /dev/null -w "%{http_code}" -X 'POST' \
+            'http://localhost:3000/api/races/keirin/calendar' \
+            -H 'accept: */*' \
+            -H 'Content-Type: application/json' \
+            -d '{
+                  "startDate": "2024-10-01",
+                  "finishDate": "2024-11-01"
+                }')
+
+          # POST Response Check
+          if [[ "$post_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $post_response"
+            exit 1
+          fi
+
+          # Updated GET request
+          response=$(curl -s -X 'GET' \
+            'http://localhost:3000/api/races/keirin/calendar?startDate=2024-10-01&finishDate=2024-11-01' \
+            -H 'accept: application/json')
+
+          # Final GET Response Check: 要素数が31個であることを確認
+          item_count=$(echo "$response" | jq '. | length')
+          if [[ "$item_count" -ne 31 ]]; then
+            echo "❌ Updated GET request failed. Expected 31 items but got $item_count items."
             exit 1
           fi
 
