batchの名称変更

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -1,4 +1,4 @@
-name: World Horse Race Schedule Batch
+name: Race Schedule Batch
 
 on:
   schedule:
@@ -38,6 +38,67 @@ jobs:
           # GITHUB_OUTPUTを使って出力設定
           echo "start-date=$startDate" >> $GITHUB_OUTPUT
           echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
+
+  update-jra-race-data:
+    needs: set-dates
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        env:
+          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # レースデータの更新
+          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/jra/race" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_data_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_data_response"
+            exit 1
+          fi
+
+  update-jra-race-calendar:
+    needs: [set-dates, update-jra-race-data]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        env:
+          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/jra/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
 
   update-world-race-data:
     needs: set-dates
