スケジュールの変更 (#153)

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -379,7 +379,35 @@ jobs:
           done
 
   update-keirin-race-calendar-g:
-    needs: [set-dates, update-keirin-race-data-g, update-keirin-race-data-f]
+    needs: [set-dates, update-keirin-race-data-g]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date-for-keirin }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/keirin/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
+
+  update-keirin-race-calendar-f:
+    needs: [set-dates, update-keirin-race-data-f]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
