batchの修正

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -13,6 +13,9 @@ on:
         description: 'Finish date (YYYY-MM-DD format)'
         required: false
 
+env:
+  API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
+
 jobs:
   set-dates:
     runs-on: ubuntu-latest
@@ -39,16 +42,30 @@ jobs:
           echo "start-date=$startDate" >> $GITHUB_OUTPUT
           echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
 
+  health-check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Start server in background
+        run: |
+          health_check_response=$(curl -s -o /dev/null -w "%{http_code}" ${API_PRODUCTION_URL}/health)
+
+          # レスポンスチェック
+          if [[ "$health_check_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $health_check_response"
+            exit 1
+          fi
+
   update-jra-race-data:
-    needs: set-dates
+    needs: [set-dates, health-check]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
 
       - name: Send curl request to API
-        env:
-          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
         run: |
           # 日付はset-datesで設定済み
           startDate="${{ needs.set-dates.outputs.start-date }}"
@@ -78,8 +95,6 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Send curl request to API
-        env:
-          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
         run: |
           startDate="${{ needs.set-dates.outputs.start-date }}"
           finishDate="${{ needs.set-dates.outputs.finish-date }}"
@@ -100,16 +115,71 @@ jobs:
             exit 1
           fi
 
-  update-world-race-data:
-    needs: set-dates
+  update-nar-race-data:
+    needs: [set-dates, health-check]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
         uses: actions/checkout@v4
 
       - name: Send curl request to API
-        env:
-          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # レースデータの更新
+          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/nar/race" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_data_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_data_response"
+            exit 1
+          fi
+
+  update-nar-race-calendar:
+    needs: [set-dates, update-nar-race-data]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/nar/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
+
+  update-world-race-data:
+    needs: [set-dates, health-check]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
         run: |
           # 日付はset-datesで設定済み
           startDate="${{ needs.set-dates.outputs.start-date }}"
@@ -139,8 +209,6 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Send curl request to API
-        env:
-          API_PRODUCTION_URL: "${{ secrets.API_PRODUCTION_URL }}"
         run: |
           startDate="${{ needs.set-dates.outputs.start-date }}"
           finishDate="${{ needs.set-dates.outputs.finish-date }}"
@@ -148,6 +216,63 @@ jobs:
           # カレンダーの更新
           update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
             "${API_PRODUCTION_URL}/api/races/world/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
+
+  update-keirin-race-data:
+    needs: [set-dates, health-check]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # レースデータの更新
+          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/keirin/race" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_data_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_data_response"
+            exit 1
+          fi
+
+  update-keirin-race-calendar:
+    needs: [set-dates, update-keirin-race-data]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/keirin/calendar" \
             -H "accept: */*" \
             -H "Content-Type: application/json" \
             -d "{
