race-schedule-batchの修正

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -294,3 +294,67 @@ jobs:
             echo "❌ POST request failed with status code $update_race_calendar_response"
             exit 1
           fi
+
+  update-keirin-race-data:
+    needs: [set-dates, health-check]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date-for-keirin }}"
+
+          currentDate="$startDate"
+          while [ "$currentDate" != "$(date -I -d "$finishDate + 1 day")" ]; do
+            echo "Processing date: $currentDate"
+
+            # カレンダーの更新
+            update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+              "${API_PRODUCTION_URL}/api/races/keirin/calendar" \
+              -H "accept: */*" \
+              -H "Content-Type: application/json" \
+              -d "{
+                    \"startDate\": \"$currentDate\",
+                    \"finishDate\": \"$currentDate\"
+                  }")
+
+            # レスポンスチェック
+            if [[ "$update_race_calendar_response" != "200" ]]; then
+              echo "❌ POST request failed with status code $update_race_calendar_response"
+              exit 1
+            fi
+
+            currentDate=$(date -I -d "$currentDate + 1 day")
+          done
+
+  update-keirin-race-calendar:
+    needs: [set-dates, update-keirin-race-data]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date-for-autorace }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/keirin/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
