batchの登録

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -25,6 +25,7 @@ jobs:
       # 競輪・オートレースは1日毎に出走表が更新されるため、finish-dateを1日後に設定
       finish-date-for-keirin: ${{ steps.set-dates.outputs.finish-date-for-keirin }}
       finish-date-for-autorace: ${{ steps.set-dates.outputs.finish-date-for-autorace }}
+      finish-date-for-boatrace: ${{ steps.set-dates.outputs.finish-date-for-boatrace }}
     steps:
       - name: Outputを設定
         id: set-dates
@@ -34,6 +35,7 @@ jobs:
           finishDate="${{ github.event.inputs.finish-date }}"
           finishDateForKeirin="${{ github.event.inputs.finish-date }}"
           finishDateForAutorace="${{ github.event.inputs.finish-date }}"
+          finishDateForBoatrace="${{ github.event.inputs.finish-date }}"
 
           # 入力がない場合のデフォルト設定
           if [ -z "$startDate" ]; then
@@ -43,6 +45,7 @@ jobs:
             finishDate=$(date -d "+2 days" +"%Y-%m-%d")
             finishDateForKeirin=$(date -d "+1 days" +"%Y-%m-%d")
             finishDateForAutorace=$(date -d "+1 day" +"%Y-%m-%d")
+            finishDateForBoatrace=$(date -d "+1 day" +"%Y-%m-%d")
           fi
 
           # GITHUB_OUTPUTを使って出力設定
@@ -50,6 +53,7 @@ jobs:
           echo "finish-date=$finishDate" >> $GITHUB_OUTPUT
           echo "finish-date-for-keirin=$finishDateForKeirin" >> $GITHUB_OUTPUT
           echo "finish-date-for-autorace=$finishDateForAutorace" >> $GITHUB_OUTPUT
+          echo "finish-date-for-boatrace=$finishDateForBoatrace" >> $GITHUB_OUTPUT
 
   health-check:
     runs-on: ubuntu-latest
@@ -346,6 +350,63 @@ jobs:
           # カレンダーの更新
           update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
             "${API_PRODUCTION_URL}/api/races/keirin/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
+
+  update-boatrace-race-data:
+    needs: [set-dates, health-check]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date-for-boatrace }}"
+
+          # レースデータの更新
+          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/boatrace/race" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_data_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_data_response"
+            exit 1
+          fi
+
+  update-boatrace-race-calendar:
+    needs: [set-dates, update-boatrace-race-data]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          startDate="${{ needs.set-dates.outputs.start-date }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date-for-boatrace }}"
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/boatrace/calendar" \
             -H "accept: */*" \
             -H "Content-Type: application/json" \
             -d "{
