racebatchを修正

diff --git a/.github/workflows/race-schedule-batch.yml b/.github/workflows/race-schedule-batch.yml
--- a/.github/workflows/race-schedule-batch.yml
+++ b/.github/workflows/race-schedule-batch.yml
@@ -340,8 +340,7 @@ jobs:
             currentDate=$(date -I -d "$currentDate + 1 day")
           done
 
-
-  update-keirin-race-data-f:
+  update-keirin-race-data-f1:
     needs: [set-dates, health-check]
     runs-on: ubuntu-latest
     steps:
@@ -366,7 +365,44 @@ jobs:
               -d "{
                     \"startDate\": \"$currentDate\",
                     \"finishDate\": \"$currentDate\",
-                    \"gradeList\": [\"FⅠ\", \"FⅡ\"]
+                    \"gradeList\": [\"FⅠ\"]
+                  }")
+
+            # レスポンスチェック
+            if [[ "$update_race_calendar_response" != "200" ]]; then
+              echo "❌ POST request failed with status code $update_race_calendar_response"
+              exit 1
+            fi
+
+            currentDate=$(date -I -d "$currentDate + 1 day")
+          done
+
+  update-keirin-race-data-f2:
+    needs: [set-dates, health-check]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v4
+
+      - name: Send curl request to API
+        run: |
+          # 日付はset-datesで設定済み
+          startDate="${{ needs.set-dates.outputs.start-date-for-keirin }}"
+          finishDate="${{ needs.set-dates.outputs.finish-date }}"
+
+          currentDate="$startDate"
+          while [ "$currentDate" != "$(date -I -d "$finishDate + 1 day")" ]; do
+            echo "Processing date: $currentDate"
+
+            # カレンダーの更新
+            update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+              "${API_PRODUCTION_URL}/api/races/keirin/race" \
+              -H "accept: */*" \
+              -H "Content-Type: application/json" \
+              -d "{
+                    \"startDate\": \"$currentDate\",
+                    \"finishDate\": \"$currentDate\",
+                    \"gradeList\": [\"FⅡ\"]
                   }")
 
             # レスポンスチェック
@@ -407,7 +443,7 @@ jobs:
           fi
 
   update-keirin-race-calendar-f:
-    needs: [set-dates, update-keirin-race-data-f]
+    needs: [set-dates, update-keirin-race-data-f1, update-keirin-race-data-f2]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
