cronの設定追加

diff --git a/.github/workflows/world-horse-race-schedule.yml b/.github/workflows/world-horse-race-schedule.yml
--- a/.github/workflows/world-horse-race-schedule.yml
+++ b/.github/workflows/world-horse-race-schedule.yml
@@ -1,24 +1,68 @@
 on:
   schedule:
     - cron: '0 21 * * *' # 毎日21時に実行
-  workflow_dispatch: # 手動トリガーを許可
+  workflow_dispatch:
+    inputs:
+      start-date:
+        description: 'Start date (YYYY-MM-DD format)'
+        required: false
+      finish-date:
+        description: 'Finish date (YYYY-MM-DD format)'
+        required: false
 
 jobs:
   world-race:
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Send curl request to API
         env:
           API_PRODUCTION_URL: ${{ secrets.API_PRODUCTION_URL }}
         run: |
-          # 日付を計算
-          startDate=$(date -d "yesterday" +"%Y-%m-%d")
-          finishDate=$(date -d "+2 days" +"%Y-%m-%d")
+          # 日付を計算、デフォルトは昨日から2日後
+          startDate="${{ github.event.inputs.start-date }}"
+          finishDate="${{ github.event.inputs.finish-date }}"
 
-          # GETリクエストを送信
-          response=$(curl -s -X GET "${API_PRODUCTION_URL}/api/races/world/calendar?startDate=${startDate}&finishDate=${finishDate}" -H "accept: application/json")
+          # 入力がない場合のデフォルト設定
+          if [ -z "$startDate" ]; then
+            startDate=$(date -d "yesterday" +"%Y-%m-%d")
+          fi
+          if [ -z "$finishDate" ]; then
+            finishDate=$(date -d "+2 days" +"%Y-%m-%d")
+          fi
 
-          echo "Response: $response"
+          # レースデータの更新
+          update_race_data_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/world/race" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_data_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_data_response"
+            exit 1
+          fi
+
+          # カレンダーの更新
+          update_race_calendar_response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            "${API_PRODUCTION_URL}/api/races/world/calendar" \
+            -H "accept: */*" \
+            -H "Content-Type: application/json" \
+            -d "{
+                  \"startDate\": \"$startDate\",
+                  \"finishDate\": \"$finishDate\"
+                }")
+
+          # レスポンスチェック
+          if [[ "$update_race_calendar_response" != "200" ]]; then
+            echo "❌ POST request failed with status code $update_race_calendar_response"
+            exit 1
+          fi
+
+          echo "✅ API requests succeeded with startDate: $startDate and finishDate: $finishDate"
